version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    image: 404332397563.dkr.ecr.us-east-2.amazonaws.com/isabl_tesis2_production_django
    command: /start
    links:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    ports:
      - "0.0.0.0:80:8000"
      - "0.0.0.0:6868:5000"
    logging:
      driver: awslogs
      options: 
        awslogs-group: logs_cluster
        awslogs-region: us-east-2
        awslogs-stream-prefix: django

  postgres:
    image: 404332397563.dkr.ecr.us-east-2.amazonaws.com/isabl_tesis2_production_postgres
    ports:
      - "5432:5432"
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    logging:
      driver: awslogs
      options: 
        awslogs-group: logs_cluster
        awslogs-region: us-east-2
        awslogs-stream-prefix: postgres

  redis:
    image: 404332397563.dkr.ecr.us-east-2.amazonaws.com/redis:3.2
    ports:
      - "6379:6379"
    logging:
      driver: awslogs
      options: 
        awslogs-group: logs_cluster
        awslogs-region: us-east-2
        awslogs-stream-prefix: redis

  celeryworker:
    <<: *django
    image: 404332397563.dkr.ecr.us-east-2.amazonaws.com/isabl_tesis2_production_celeryworker
    links:
      - redis
      - postgres
    ports: []
    logging:
      driver: awslogs
      options: 
        awslogs-group: logs_cluster
        awslogs-region: us-east-2
        awslogs-stream-prefix: celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: 404332397563.dkr.ecr.us-east-2.amazonaws.com/isabl_tesis2_production_celerybeat
    links:
      - redis
      - postgres
    ports: []
    logging:
      driver: awslogs
      options: 
        awslogs-group: logs_cluster
        awslogs-region: us-east-2
        awslogs-stream-prefix: celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: 404332397563.dkr.ecr.us-east-2.amazonaws.com/isabl_tesis2_production_flower
    ports:
      - "5555:5555"
    logging:
      driver: awslogs
      options: 
        awslogs-group: logs_cluster
        awslogs-region: us-east-2
        awslogs-stream-prefix: flower
    command: /start-flower
